### ISSUE TITLE
Loading project requires permissions

### ISSUE THREAD

**Issue by dionisiydk** [pharo-graphics/Brick#3]
No when I load Brik I got this error:

Git error: Cloning into ''Brick''...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by GlennCavarle** [comment]
What version are you trying to load?

The ["User"](https://github.com/pharo-graphics/Brick#all-in-one-user-versions) version should work without  to be forced to  [register an SSH key](https://help.github.com/articles/generating-an-ssh-key/) on Github but the ["Developer"](https://github.com/pharo-graphics/Brick#all-in-one-developer-versions) version still need it because of [Iceberg pre-requisites](https://github.com/npasserini/iceberg#prerequisites).

Keep me informed if you face the same issue with the "User" version.

**Comment by dionisiydk** [comment]
Thank's Glenn. It works. And now I could play with it.

**Comment by GlennCavarle** [comment]
Be aware that Brick is at an early early stage of development ;)
Have fun and thanks for your interest Denis.
